const colorslist = [
    [
    {"name": "Alice blue", "hex": "#F0F8FF"},
    {"name": "Antique white", "hex": "#FAEBD7"},
    {"name": "Aqua", "hex": "#00FFFF"},
    {"name": "Aquamarine", "hex": "#7FFFD4"},
    {"name": "Azure", "hex": "#F0FFFF"},
    {"name": "Beige", "hex": "#F5F5DC"},
    {"name": "Bisque", "hex": "#FFE4C4"},
    {"name": "Black", "hex": "#000000"},
    {"name": "Blanched almond", "hex": "#FFEBCD"},
    {"name": "Blue", "hex": "#0000FF"},
    {"name": "Blue violet", "hex": "#8A2BE2"},
    {"name": "Brown", "hex": "#A52A2A"},
    {"name": "Burlywood", "hex": "#DEB887"},
    {"name": "Cadet blue", "hex": "#5F9EA0"},
    {"name": "Chartreuse", "hex": "#7FFF00"},
    {"name": "Chocolate", "hex": "#D2691E"},
    {"name": "Coral", "hex": "#FF7F50"},
    {"name": "Cornflower blue", "hex": "#6495ED"},
    {"name": "Cornsilk", "hex": "#FFF8DC"},
    {"name": "Crimson", "hex": "#DC143C"},
    {"name": "Cyan", "hex": "#00FFFF"},
    {"name": "Dark blue", "hex": "#00008B"},
    {"name": "Dark cyan", "hex": "#008B8B"},
    {"name": "Dark goldenrod", "hex": "#B8860B"},
    {"name": "Dark gray", "hex": "#A9A9A9"},
    {"name": "Dark green", "hex": "#006400"},
    {"name": "Dark khaki", "hex": "#BDB76B"},
    {"name": "Dark magenta", "hex": "#8B008B"},
    {"name": "Dark olive green", "hex": "#556B2F"},
    {"name": "Dark orange", "hex": "#FF8C00"},
    {"name": "Dark orchid", "hex": "#9932CC"},
    {"name": "Dark red", "hex": "#8B0000"},
    {"name": "Dark salmon", "hex": "#E9967A"},
    {"name": "Dark seagreen", "hex": "#8DBC8F"},
    {"name": "Dark slate blue", "hex": "#483D8B"},
    {"name": "Dark slate gray", "hex": "#2F4F4F"},
    {"name": "Dark turquoise", "hex": "#00DED1"},
    {"name": "Dark violet", "hex": "#9400D3"},
    {"name": "Deep pink", "hex": "#FF1493"},
    {"name": "Deep sky blue", "hex": "#00BFFF"},
    {"name": "Dim gray", "hex": "#696969"},
    {"name": "Dodger blue", "hex": "#1E90FF"},
    {"name": "Firebrick", "hex": "#B22222"},
    {"name": "Floral white", "hex": "#FFFAF0"},
    {"name": "Forest green", "hex": "#228B22"},
    {"name": "Fuchsia", "hex": "#FF00FF"},
    {"name": "Gainsboro", "hex": "#DCDCDC"},
    {"name": "Ghost white", "hex": "#F8F8FF"},
    {"name": "Gold", "hex": "#FFD700"},
    {"name": "Goldenrod", "hex": "#DAA520"},
    {"name": "Gray", "hex": "#808080"},
    {"name": "Green", "hex": "#008000"},
    {"name": "Green yellow", "hex": "#ADFF2F"},
    {"name": "Honeydew", "hex": "#F0FFF0"},
    {"name": "Hot pink", "hex": "#FF69B4"},
    {"name": "Indian red", "hex": "#CD5C5C"},
    {"name": "Indigo", "hex": "#4B0082"},
    {"name": "Ivory", "hex": "#FFFFF0"},
    {"name": "Khaki", "hex": "#F0E68C"},
    {"name": "Lavender", "hex": "#E6E6FA"},
    {"name": "Lavender blush", "hex": "#FFF0F5"},
    {"name": "Lawn green", "hex": "#7CFC00"},
    {"name": "Lemon chiffon", "hex": "#FFFACD"},
    {"name": "Light blue", "hex": "#ADD8E6"},
    {"name": "Light coral", "hex": "#F08080"},
    {"name": "Light cyan", "hex": "#E0FFFF"},
    {"name": "Light goldenrod yellow", "hex": "#FAFAD2"},
    {"name": "Light green", "hex": "#90EE90"},
    {"name": "Light grey", "hex": "#D3D3D3"},
    {"name": "Light pink", "hex": "#FFB6C1"},
    {"name": "Light salmon", "hex": "#FFA07A"},
    {"name": "Light sea green", "hex": "#20B2AA"},
    {"name": "Light sky blue", "hex": "#87CEFA"},
    {"name": "Light slate gray", "hex": "#778899"},
    {"name": "Light steel blue", "hex": "#B0C4DE"},
    {"name": "Light yellow", "hex": "#FFFFE0"},
    {"name": "Lime", "hex": "#00FF00"},
    {"name": "Lime green", "hex": "#32CD32"},
    {"name": "Linen", "hex": "#FAF0E6"},
    {"name": "Magenta", "hex": "#FF00FF"},
    {"name": "Maroon", "hex": "#800000"},
    {"name": "Medium aquamarine", "hex": "#66CDAA"},
    {"name": "Medium blue", "hex": "#0000CD"},
    {"name": "Medium orchid", "hex": "#BA55D3"},
    {"name": "Medium purple", "hex": "#9370DB"},
    {"name": "Medium sea green", "hex": "#3CB371"},
    {"name": "Medium slate blue", "hex": "#7B68EE"},
    {"name": "Medium spring green", "hex": "#00FA9A"},
    {"name": "Medium turquoise", "hex": "#48D1CC"},
    {"name": "Medium violet red", "hex": "#C71585"},
    {"name": "Midnight blue", "hex": "#191970"},
    {"name": "Mint cream", "hex": "#F5FFFA"},
    {"name": "Misty rose", "hex": "#FFE4E1"},
    {"name": "Moccasin", "hex": "#FFE4B5"},
    {"name": "Navajo white", "hex": "#FFDEAD"},
    {"name": "Navy", "hex": "#000080"},
    {"name": "Old lace", "hex": "#FDF5E6"},
    {"name": "Olive drab", "hex": "#6B8E23"},
    {"name": "Orange", "hex": "#FFA500"},
    {"name": "Orange red", "hex": "#FF4500"},
    {"name": "Orchid", "hex": "#DA70D6"},
    {"name": "Pale goldenrod", "hex": "#EEE8AA"},
    {"name": "Pale green", "hex": "#98FB98"},
    {"name": "Pale turquoise", "hex": "#AFEEEE"},
    {"name": "Pale violet red", "hex": "#DB7093"},
    {"name": "Papaya whip", "hex": "#FFEFD5"},
    {"name": "Peach puff", "hex": "#FFDAB9"},
    {"name": "Peru", "hex": "#CD853F"},
    {"name": "Pink", "hex": "#FFC8CB"},
    {"name": "Plum", "hex": "#DDA0DD"},
    {"name": "Powder blue", "hex": "#B0E0E6"},
    {"name": "Purple", "hex": "#800080"},
    {"name": "Red", "hex": "#FF0000"},
    {"name": "Rosy brown", "hex": "#BC8F8F"},
    {"name": "Royal blue", "hex": "#4169E1"},
    {"name": "Saddle brown", "hex": "#8B4513"},
    {"name": "Salmon", "hex": "#FA8072"},
    {"name": "Sandy brown", "hex": "#F4A460"},
    {"name": "Sea green", "hex": "#2E8B57"},
    {"name": "Sea shell", "hex": "#FFF5EE"},
    {"name": "Sienna", "hex": "#A0522D"},
    {"name": "Silver", "hex": "#C0C0C0"},
    {"name": "Sky blue", "hex": "#87CEEB"},
    {"name": "Slate blue", "hex": "#6A5ACD"},
    {"name": "Snow", "hex": "#FFFAFA"},
    {"name": "Spring green", "hex": "#00FF7F"},
    {"name": "Steel blue", "hex": "#4682B4"},
    {"name": "Tan", "hex": "#D2B48C"},
    {"name": "Thistle", "hex": "#D8BFD8"},
    {"name": "Teal", "hex": "#008080"},
    {"name": "Tomato", "hex": "#FF6347"},
    {"name": "Turquoise", "hex": "#40E0D0"},
    {"name": "Violet", "hex": "#EE82EE"},
    {"name": "Wheat", "hex": "#F5DEB3"},
    {"name": "White", "hex": "#FFFFFF"},
    {"name": "Whitesmoke", "hex": "#F5F5F5"},
    {"name": "Yellow", "hex": "#FFFF00"},
    {"name": "Yellow green", "hex": "#9ACD32"}
      ]
      
];

